version: "3.7"
services:
  app:
    depends_on:
      - db
    image: livemgr-webui:latest
    restart: always
    ports:
      - 8000:8000
  db:
    image: mariadb:10.4.13
    restart: on-failure
    volumes:
      - ./bootstrap/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306


